
/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`mfdata` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `mfdata`;

DROP TABLE IF EXISTS `mfdir`;


CREATE TABLE `mfdir` (
  `mfId` varchar(30) NOT NULL,
  `id` int(2) NOT NULL,
  `name` varchar(256) NOT NULL,
  
  PRIMARY KEY (`mfId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


commit;